// Generated by https://github.com/juliettef/IconFontCppHeaders script GenerateIconFontCppHeaders.py for languages C and C++
// from https://github.com/FortAwesome/Font-Awesome/raw/6.x/metadata/icons.yml
// for use with https://github.com/FortAwesome/Font-Awesome/blob/6.x/webfonts/fa-brands-400.ttf
#pragma once

#define FONT_ICON_FILE_NAME_FAB "fa-brands-400.ttf"

#define ICON_MIN_FAB 0xe007
#define ICON_MAX_16_FAB 0xf8e8
#define ICON_MAX_FAB 0xf8e8
#define ICON_FA_42_GROUP "\xee\x82\x80"
#define ICON_FA_500PX "\xef\x89\xae"
#define ICON_FA_ACCESSIBLE_ICON "\xef\x8d\xa8"
#define ICON_FA_ACCUSOFT "\xef\x8d\xa9"
#define ICON_FA_ADN "\xef\x85\xb0"
#define ICON_FA_ADVERSAL "\xef\x8d\xaa"
#define ICON_FA_AFFILIATETHEME "\xef\x8d\xab"
#define ICON_FA_AIRBNB "\xef\xa0\xb4"
#define ICON_FA_ALGOLIA "\xef\x8d\xac"
#define ICON_FA_ALIPAY "\xef\x99\x82"
#define ICON_FA_AMAZON "\xef\x89\xb0"
#define ICON_FA_AMAZON_PAY "\xef\x90\xac"
#define ICON_FA_AMILIA "\xef\x8d\xad"
#define ICON_FA_ANDROID "\xef\x85\xbb"
#define ICON_FA_ANGELLIST "\xef\x88\x89"
#define ICON_FA_ANGRYCREATIVE "\xef\x8d\xae"	// U+f36e
#define ICON_FA_ANGULAR "\xef\x90\xa0"	// U+f420
#define ICON_FA_APP_STORE "\xef\x8d\xaf"	// U+f36f
#define ICON_FA_APP_STORE_IOS "\xef\x8d\xb0"	// U+f370
#define ICON_FA_APPER "\xef\x8d\xb1"	// U+f371
#define ICON_FA_APPLE "\xef\x85\xb9"	// U+f179
#define ICON_FA_APPLE_PAY "\xef\x90\x95"	// U+f415
#define ICON_FA_ARTSTATION "\xef\x9d\xba"	// U+f77a
#define ICON_FA_ASYMMETRIK "\xef\x8d\xb2"	// U+f372
#define ICON_FA_ATLASSIAN "\xef\x9d\xbb"	// U+f77b
#define ICON_FA_AUDIBLE "\xef\x8d\xb3"	// U+f373
#define ICON_FA_AUTOPREFIXER "\xef\x90\x9c"	// U+f41c
#define ICON_FA_AVIANEX "\xef\x8d\xb4"	// U+f374
#define ICON_FA_AVIATO "\xef\x90\xa1"	// U+f421
#define ICON_FA_AWS "\xef\x8d\xb5"	// U+f375
#define ICON_FA_BANDCAMP "\xef\x8b\x95"	// U+f2d5
#define ICON_FA_BATTLE_NET "\xef\xa0\xb5"	// U+f835
#define ICON_FA_BEHANCE "\xef\x86\xb4"	// U+f1b4
#define ICON_FA_BILIBILI "\xee\x8f\x99"	// U+e3d9
#define ICON_FA_BIMOBJECT "\xef\x8d\xb8"	// U+f378
#define ICON_FA_BITBUCKET "\xef\x85\xb1"	// U+f171
#define ICON_FA_BITCOIN "\xef\x8d\xb9"	// U+f379
#define ICON_FA_BITY "\xef\x8d\xba"	// U+f37a
#define ICON_FA_BLACK_TIE "\xef\x89\xbe"	// U+f27e
#define ICON_FA_BLACKBERRY "\xef\x8d\xbb"	// U+f37b
#define ICON_FA_BLOGGER "\xef\x8d\xbc"	// U+f37c
#define ICON_FA_BLOGGER_B "\xef\x8d\xbd"	// U+f37d
#define ICON_FA_BLUETOOTH "\xef\x8a\x93"	// U+f293
#define ICON_FA_BLUETOOTH_B "\xef\x8a\x94"	// U+f294
#define ICON_FA_BOOTSTRAP "\xef\xa0\xb6"	// U+f836
#define ICON_FA_BOTS "\xee\x8d\x80"	// U+e340
#define ICON_FA_BTC "\xef\x85\x9a"	// U+f15a
#define ICON_FA_BUFFER "\xef\xa0\xb7"	// U+f837
#define ICON_FA_BUROMOBELEXPERTE "\xef\x8d\xbf"	// U+f37f
#define ICON_FA_BUY_N_LARGE "\xef\xa2\xa6"	// U+f8a6
#define ICON_FA_BUYSELLADS "\xef\x88\x8d"	// U+f20d
#define ICON_FA_CANADIAN_MAPLE_LEAF "\xef\x9e\x85"	// U+f785
#define ICON_FA_CC_AMAZON_PAY "\xef\x90\xad"	// U+f42d
#define ICON_FA_CC_AMEX "\xef\x87\xb3"	// U+f1f3
#define ICON_FA_CC_APPLE_PAY "\xef\x90\x96"	// U+f416
#define ICON_FA_CC_DINERS_CLUB "\xef\x89\x8c"	// U+f24c
#define ICON_FA_CC_DISCOVER "\xef\x87\xb2"	// U+f1f2
#define ICON_FA_CC_JCB "\xef\x89\x8b"	// U+f24b
#define ICON_FA_CC_MASTERCARD "\xef\x87\xb1"	// U+f1f1
#define ICON_FA_CC_PAYPAL "\xef\x87\xb4"	// U+f1f4
#define ICON_FA_CC_STRIPE "\xef\x87\xb5"	// U+f1f5
#define ICON_FA_CC_VISA "\xef\x87\xb0"	// U+f1f0
#define ICON_FA_CENTERCODE "\xef\x8e\x80"	// U+f380
#define ICON_FA_CENTOS "\xef\x9e\x89"	// U+f789
#define ICON_FA_CHROME "\xef\x89\xa8"	// U+f268
#define ICON_FA_CHROMECAST "\xef\xa0\xb8"	// U+f838
#define ICON_FA_CLOUDFLARE "\xee\x81\xbd"	// U+e07d
#define ICON_FA_CLOUDSCALE "\xef\x8e\x83"	// U+f383
#define ICON_FA_CLOUDSMITH "\xef\x8e\x84"	// U+f384
#define ICON_FA_CLOUDVERSIFY "\xef\x8e\x85"	// U+f385
#define ICON_FA_CMPLID "\xee\x8d\xa0"	// U+e360
#define ICON_FA_CODEPEN "\xef\x87\x8b"	// U+f1cb
#define ICON_FA_CODIEPIE "\xef\x8a\x84"	// U+f284
#define ICON_FA_CONFLUENCE "\xef\x9e\x8d"	// U+f78d
#define ICON_FA_CONNECTDEVELOP "\xef\x88\x8e"	// U+f20e
#define ICON_FA_CONTAO "\xef\x89\xad"	// U+f26d
#define ICON_FA_COTTON_BUREAU "\xef\xa2\x9e"	// U+f89e
#define ICON_FA_CPANEL "\xef\x8e\x88"	// U+f388
#define ICON_FA_CREATIVE_COMMONS "\xef\x89\x9e"	// U+f25e
#define ICON_FA_CREATIVE_COMMONS_BY "\xef\x93\xa7"	// U+f4e7
#define ICON_FA_CREATIVE_COMMONS_NC "\xef\x93\xa8"	// U+f4e8
#define ICON_FA_CREATIVE_COMMONS_NC_EU "\xef\x93\xa9"	// U+f4e9
#define ICON_FA_CREATIVE_COMMONS_NC_JP "\xef\x93\xaa"	// U+f4ea
#define ICON_FA_CREATIVE_COMMONS_ND "\xef\x93\xab"	// U+f4eb
#define ICON_FA_CREATIVE_COMMONS_PD "\xef\x93\xac"	// U+f4ec
#define ICON_FA_CREATIVE_COMMONS_PD_ALT "\xef\x93\xad"	// U+f4ed
#define ICON_FA_CREATIVE_COMMONS_REMIX "\xef\x93\xae"	// U+f4ee
#define ICON_FA_CREATIVE_COMMONS_SA "\xef\x93\xaf"	// U+f4ef
#define ICON_FA_CREATIVE_COMMONS_SAMPLING "\xef\x93\xb0"	// U+f4f0
#define ICON_FA_CREATIVE_COMMONS_SAMPLING_PLUS "\xef\x93\xb1"	// U+f4f1
#define ICON_FA_CREATIVE_COMMONS_SHARE "\xef\x93\xb2"	// U+f4f2
#define ICON_FA_CREATIVE_COMMONS_ZERO "\xef\x93\xb3"	// U+f4f3
#define ICON_FA_CRITICAL_ROLE "\xef\x9b\x89"	// U+f6c9
#define ICON_FA_CSS3 "\xef\x84\xbc"	// U+f13c
#define ICON_FA_CSS3_ALT "\xef\x8e\x8b"	// U+f38b
#define ICON_FA_CUTTLEFISH "\xef\x8e\x8c"	// U+f38c
#define ICON_FA_D_AND_D "\xef\x8e\x8d"	// U+f38d
#define ICON_FA_D_AND_D_BEYOND "\xef\x9b\x8a"	// U+f6ca
#define ICON_FA_DAILYMOTION "\xee\x81\x92"	// U+e052
#define ICON_FA_DASHCUBE "\xef\x88\x90"	// U+f210
#define ICON_FA_DEBIAN "\xee\x98\x8b"	// U+e60b
#define ICON_FA_DEEZER "\xee\x81\xb7"	// U+e077
#define ICON_FA_DELICIOUS "\xef\x86\xa5"	// U+f1a5
#define ICON_FA_DEPLOYDOG "\xef\x8e\x8e"	// U+f38e
#define ICON_FA_DESKPRO "\xef\x8e\x8f"	// U+f38f
#define ICON_FA_DEV "\xef\x9b\x8c"	// U+f6cc
#define ICON_FA_DEVIANTART "\xef\x86\xbd"	// U+f1bd
#define ICON_FA_DHL "\xef\x9e\x90"	// U+f790
#define ICON_FA_DIASPORA "\xef\x9e\x91"	// U+f791
#define ICON_FA_DIGG "\xef\x86\xa6"	// U+f1a6
#define ICON_FA_DIGITAL_OCEAN "\xef\x8e\x91"	// U+f391
#define ICON_FA_DISCORD "\xef\x8e\x92"	// U+f392
#define ICON_FA_DISCOURSE "\xef\x8e\x93"	// U+f393
#define ICON_FA_DOCHUB "\xef\x8e\x94"	// U+f394
#define ICON_FA_DOCKER "\xef\x8e\x95"	// U+f395
#define ICON_FA_DRAFT2DIGITAL "\xef\x8e\x96"	// U+f396
#define ICON_FA_DRIBBBLE "\xef\x85\xbd"	// U+f17d
#define ICON_FA_DROPBOX "\xef\x85\xab"	// U+f16b
#define ICON_FA_DRUPAL "\xef\x86\xa9"	// U+f1a9
#define ICON_FA_DYALOG "\xef\x8e\x99"	// U+f399
#define ICON_FA_EARLYBIRDS "\xef\x8e\x9a"	// U+f39a
#define ICON_FA_EBAY "\xef\x93\xb4"	// U+f4f4
#define ICON_FA_EDGE "\xef\x8a\x82"	// U+f282
#define ICON_FA_EDGE_LEGACY "\xee\x81\xb8"	// U+e078
#define ICON_FA_ELEMENTOR "\xef\x90\xb0"	// U+f430
#define ICON_FA_ELLO "\xef\x97\xb1"	// U+f5f1
#define ICON_FA_EMBER "\xef\x90\xa3"	// U+f423
#define ICON_FA_EMPIRE "\xef\x87\x91"	// U+f1d1
#define ICON_FA_ENVIRA "\xef\x8a\x99"	// U+f299
#define ICON_FA_ERLANG "\xef\x8e\x9d"	// U+f39d
#define ICON_FA_ETHEREUM "\xef\x90\xae"	// U+f42e
#define ICON_FA_ETSY "\xef\x8b\x97"	// U+f2d7
#define ICON_FA_EVERNOTE "\xef\xa0\xb9"	// U+f839
#define ICON_FA_EXPEDITEDSSL "\xef\x88\xbe"	// U+f23e
#define ICON_FA_FACEBOOK "\xef\x82\x9a"	// U+f09a
#define ICON_FA_FACEBOOK_F "\xef\x8e\x9e"	// U+f39e
#define ICON_FA_FACEBOOK_MESSENGER "\xef\x8e\x9f"	// U+f39f
#define ICON_FA_FANTASY_FLIGHT_GAMES "\xef\x9b\x9c"	// U+f6dc
#define ICON_FA_FEDEX "\xef\x9e\x97"	// U+f797
#define ICON_FA_FEDORA "\xef\x9e\x98"	// U+f798
#define ICON_FA_FIGMA "\xef\x9e\x99"	// U+f799
#define ICON_FA_FIREFOX "\xef\x89\xa9"	// U+f269
#define ICON_FA_FIREFOX_BROWSER "\xee\x80\x87"	// U+e007
#define ICON_FA_FIRST_ORDER "\xef\x8a\xb0"	// U+f2b0
#define ICON_FA_FIRST_ORDER_ALT "\xef\x94\x8a"	// U+f50a
#define ICON_FA_FIRSTDRAFT "\xef\x8e\xa1"	// U+f3a1
#define ICON_FA_FLICKR "\xef\x85\xae"	// U+f16e
#define ICON_FA_FLIPBOARD "\xef\x91\x8d"	// U+f44d
#define ICON_FA_FLY "\xef\x90\x97"	// U+f417
#define ICON_FA_FONT_AWESOME "\xef\x8a\xb4"	// U+f2b4
#define ICON_FA_FONTICONS "\xef\x8a\x80"	// U+f280
#define ICON_FA_FONTICONS_FI "\xef\x8e\xa2"	// U+f3a2
#define ICON_FA_FORT_AWESOME "\xef\x8a\x86"	// U+f286
#define ICON_FA_FORT_AWESOME_ALT "\xef\x8e\xa3"	// U+f3a3
#define ICON_FA_FORUMBEE "\xef\x88\x91"	// U+f211
#define ICON_FA_FOURSQUARE "\xef\x86\x80"	// U+f180
#define ICON_FA_FREE_CODE_CAMP "\xef\x8b\x85"	// U+f2c5
#define ICON_FA_FREEBSD "\xef\x8e\xa4"	// U+f3a4
#define ICON_FA_FULCRUM "\xef\x94\x8b"	// U+f50b
#define ICON_FA_GALACTIC_REPUBLIC "\xef\x94\x8c"	// U+f50c
#define ICON_FA_GALACTIC_SENATE "\xef\x94\x8d"	// U+f50d
#define ICON_FA_GET_POCKET "\xef\x89\xa5"	// U+f265
#define ICON_FA_GG "\xef\x89\xa0"	// U+f260
#define ICON_FA_GG_CIRCLE "\xef\x89\xa1"	// U+f261
#define ICON_FA_GIT "\xef\x87\x93"	// U+f1d3
#define ICON_FA_GIT_ALT "\xef\xa1\x81"	// U+f841
#define ICON_FA_GITHUB "\xef\x82\x9b"	// U+f09b
#define ICON_FA_GITHUB_ALT "\xef\x84\x93"	// U+f113
#define ICON_FA_GITKRAKEN "\xef\x8e\xa6"	// U+f3a6
#define ICON_FA_GITLAB "\xef\x8a\x96"	// U+f296
#define ICON_FA_GITTER "\xef\x90\xa6"	// U+f426
#define ICON_FA_GLIDE "\xef\x8a\xa5"	// U+f2a5
#define ICON_FA_GLIDE_G "\xef\x8a\xa6"	// U+f2a6
#define ICON_FA_GOFORE "\xef\x8e\xa7"	// U+f3a7
#define ICON_FA_GOLANG "\xee\x90\x8f"	// U+e40f
#define ICON_FA_GOODREADS "\xef\x8e\xa8"	// U+f3a8
#define ICON_FA_GOODREADS_G "\xef\x8e\xa9"	// U+f3a9
#define ICON_FA_GOOGLE "\xef\x86\xa0"	// U+f1a0
#define ICON_FA_GOOGLE_DRIVE "\xef\x8e\xaa"	// U+f3aa
#define ICON_FA_GOOGLE_PAY "\xee\x81\xb9"	// U+e079
#define ICON_FA_GOOGLE_PLAY "\xef\x8e\xab"	// U+f3ab
#define ICON_FA_GOOGLE_PLUS "\xef\x8a\xb3"	// U+f2b3
#define ICON_FA_GOOGLE_PLUS_G "\xef\x83\x95"	// U+f0d5
#define ICON_FA_GOOGLE_WALLET "\xef\x87\xae"	// U+f1ee
#define ICON_FA_GRATIPAY "\xef\x86\x84"	// U+f184
#define ICON_FA_GRAV "\xef\x8b\x96"	// U+f2d6
#define ICON_FA_GRIPFIRE "\xef\x8e\xac"	// U+f3ac
#define ICON_FA_GRUNT "\xef\x8e\xad"	// U+f3ad
#define ICON_FA_GUILDED "\xee\x81\xbe"	// U+e07e
#define ICON_FA_GULP "\xef\x8e\xae"	// U+f3ae
#define ICON_FA_HACKER_NEWS "\xef\x87\x94"	// U+f1d4
#define ICON_FA_HACKERRANK "\xef\x97\xb7"	// U+f5f7
#define ICON_FA_HASHNODE "\xee\x92\x99"	// U+e499
#define ICON_FA_HIPS "\xef\x91\x92"	// U+f452
#define ICON_FA_HIRE_A_HELPER "\xef\x8e\xb0"	// U+f3b0
#define ICON_FA_HIVE "\xee\x81\xbf"	// U+e07f
#define ICON_FA_HOOLI "\xef\x90\xa7"	// U+f427
#define ICON_FA_HORNBILL "\xef\x96\x92"	// U+f592
#define ICON_FA_HOTJAR "\xef\x8e\xb1"	// U+f3b1
#define ICON_FA_HOUZZ "\xef\x89\xbc"	// U+f27c
#define ICON_FA_HTML5 "\xef\x84\xbb"	// U+f13b
#define ICON_FA_HUBSPOT "\xef\x8e\xb2"	// U+f3b2
#define ICON_FA_IDEAL "\xee\x80\x93"	// U+e013
#define ICON_FA_IMDB "\xef\x8b\x98"	// U+f2d8
#define ICON_FA_INSTAGRAM "\xef\x85\xad"	// U+f16d
#define ICON_FA_INSTALOD "\xee\x82\x81"	// U+e081
#define ICON_FA_INTERCOM "\xef\x9e\xaf"	// U+f7af
#define ICON_FA_INTERNET_EXPLORER "\xef\x89\xab"	// U+f26b
#define ICON_FA_INVISION "\xef\x9e\xb0"	// U+f7b0
#define ICON_FA_IOXHOST "\xef\x88\x88"	// U+f208
#define ICON_FA_ITCH_IO "\xef\xa0\xba"	// U+f83a
#define ICON_FA_ITUNES "\xef\x8e\xb4"	// U+f3b4
#define ICON_FA_ITUNES_NOTE "\xef\x8e\xb5"	// U+f3b5
#define ICON_FA_JAVA "\xef\x93\xa4"	// U+f4e4
#define ICON_FA_JEDI_ORDER "\xef\x94\x8e"	// U+f50e
#define ICON_FA_JENKINS "\xef\x8e\xb6"	// U+f3b6
#define ICON_FA_JIRA "\xef\x9e\xb1"	// U+f7b1
#define ICON_FA_JOGET "\xef\x8e\xb7"	// U+f3b7
#define ICON_FA_JOOMLA "\xef\x86\xaa"	// U+f1aa
#define ICON_FA_JS "\xef\x8e\xb8"	// U+f3b8
#define ICON_FA_JSFIDDLE "\xef\x87\x8c"	// U+f1cc
#define ICON_FA_KAGGLE "\xef\x97\xba"	// U+f5fa
#define ICON_FA_KEYBASE "\xef\x93\xb5"	// U+f4f5
#define ICON_FA_KEYCDN "\xef\x8e\xba"	// U+f3ba
#define ICON_FA_KICKSTARTER "\xef\x8e\xbb"	// U+f3bb
#define ICON_FA_KICKSTARTER_K "\xef\x8e\xbc"	// U+f3bc
#define ICON_FA_KORVUE "\xef\x90\xaf"	// U+f42f
#define ICON_FA_LARAVEL "\xef\x8e\xbd"	// U+f3bd
#define ICON_FA_LASTFM "\xef\x88\x82"	// U+f202
#define ICON_FA_LEANPUB "\xef\x88\x92"	// U+f212
#define ICON_FA_LESS "\xef\x90\x9d"	// U+f41d
#define ICON_FA_LINE "\xef\x8f\x80"	// U+f3c0
#define ICON_FA_LINKEDIN "\xef\x82\x8c"	// U+f08c
#define ICON_FA_LINKEDIN_IN "\xef\x83\xa1"	// U+f0e1
#define ICON_FA_LINODE "\xef\x8a\xb8"	// U+f2b8
#define ICON_FA_LINUX "\xef\x85\xbc"	// U+f17c
#define ICON_FA_LYFT "\xef\x8f\x83"	// U+f3c3
#define ICON_FA_MAGENTO "\xef\x8f\x84"	// U+f3c4
#define ICON_FA_MAILCHIMP "\xef\x96\x9e"	// U+f59e
#define ICON_FA_MANDALORIAN "\xef\x94\x8f"	// U+f50f
#define ICON_FA_MARKDOWN "\xef\x98\x8f"	// U+f60f
#define ICON_FA_MASTODON "\xef\x93\xb6"	// U+f4f6
#define ICON_FA_MAXCDN "\xef\x84\xb6"	// U+f136
#define ICON_FA_MDB "\xef\xa3\x8a"	// U+f8ca
#define ICON_FA_MEDAPPS "\xef\x8f\x86"	// U+f3c6
#define ICON_FA_MEDIUM "\xef\x88\xba"	// U+f23a
#define ICON_FA_MEDRT "\xef\x8f\x88"	// U+f3c8
#define ICON_FA_MEETUP "\xef\x8b\xa0"	// U+f2e0
#define ICON_FA_MEGAPORT "\xef\x96\xa3"	// U+f5a3
#define ICON_FA_MENDELEY "\xef\x9e\xb3"	// U+f7b3
#define ICON_FA_META "\xee\x92\x9b"	// U+e49b
#define ICON_FA_MICROBLOG "\xee\x80\x9a"	// U+e01a
#define ICON_FA_MICROSOFT "\xef\x8f\x8a"	// U+f3ca
#define ICON_FA_MIX "\xef\x8f\x8b"	// U+f3cb
#define ICON_FA_MIXCLOUD "\xef\x8a\x89"	// U+f289
#define ICON_FA_MIXER "\xee\x81\x96"	// U+e056
#define ICON_FA_MIZUNI "\xef\x8f\x8c"	// U+f3cc
#define ICON_FA_MODX "\xef\x8a\x85"	// U+f285
#define ICON_FA_MONERO "\xef\x8f\x90"	// U+f3d0
#define ICON_FA_NAPSTER "\xef\x8f\x92"	// U+f3d2
#define ICON_FA_NEOS "\xef\x98\x92"	// U+f612
#define ICON_FA_NFC_DIRECTIONAL "\xee\x94\xb0"	// U+e530
#define ICON_FA_NFC_SYMBOL "\xee\x94\xb1"	// U+e531
#define ICON_FA_NIMBLR "\xef\x96\xa8"	// U+f5a8
#define ICON_FA_NODE "\xef\x90\x99"	// U+f419
#define ICON_FA_NODE_JS "\xef\x8f\x93"	// U+f3d3
#define ICON_FA_NPM "\xef\x8f\x94"	// U+f3d4
#define ICON_FA_NS8 "\xef\x8f\x95"	// U+f3d5
#define ICON_FA_NUTRITIONIX "\xef\x8f\x96"	// U+f3d6
#define ICON_FA_OCTOPUS_DEPLOY "\xee\x82\x82"	// U+e082
#define ICON_FA_ODNOKLASSNIKI "\xef\x89\xa3"	// U+f263
#define ICON_FA_ODYSEE "\xee\x97\x86"	// U+e5c6
#define ICON_FA_OLD_REPUBLIC "\xef\x94\x90"	// U+f510
#define ICON_FA_OPENCART "\xef\x88\xbd"	// U+f23d
#define ICON_FA_OPENID "\xef\x86\x9b"	// U+f19b
#define ICON_FA_OPERA "\xef\x89\xaa"	// U+f26a
#define ICON_FA_OPTIN_MONSTER "\xef\x88\xbc"	// U+f23c
#define ICON_FA_ORCID "\xef\xa3\x92"	// U+f8d2
#define ICON_FA_OSI "\xef\x90\x9a"	// U+f41a
#define ICON_FA_PADLET "\xee\x92\xa0"	// U+e4a0
#define ICON_FA_PAGE4 "\xef\x8f\x97"	// U+f3d7
#define ICON_FA_PAGELINES "\xef\x86\x8c"	// U+f18c
#define ICON_FA_PALFED "\xef\x8f\x98"	// U+f3d8
#define ICON_FA_PATREON "\xef\x8f\x99"	// U+f3d9
#define ICON_FA_PAYPAL "\xef\x87\xad"	// U+f1ed
#define ICON_FA_PERBYTE "\xee\x82\x83"	// U+e083
#define ICON_FA_PERISCOPE "\xef\x8f\x9a"	// U+f3da
#define ICON_FA_PHABRICATOR "\xef\x8f\x9b"	// U+f3db
#define ICON_FA_PHOENIX_FRAMEWORK "\xef\x8f\x9c"	// U+f3dc
#define ICON_FA_PHOENIX_SQUADRON "\xef\x94\x91"	// U+f511
#define ICON_FA_PHP "\xef\x91\x97"	// U+f457
#define ICON_FA_PIED_PIPER "\xef\x8a\xae"	// U+f2ae
#define ICON_FA_PIED_PIPER_ALT "\xef\x86\xa8"	// U+f1a8
#define ICON_FA_PIED_PIPER_HAT "\xef\x93\xa5"	// U+f4e5
#define ICON_FA_PIED_PIPER_PP "\xef\x86\xa7"	// U+f1a7
#define ICON_FA_PINTEREST "\xef\x83\x92"	// U+f0d2
#define ICON_FA_PINTEREST_P "\xef\x88\xb1"	// U+f231
#define ICON_FA_PIX "\xee\x90\xba"	// U+e43a
#define ICON_FA_PLAYSTATION "\xef\x8f\x9f"	// U+f3df
#define ICON_FA_PRODUCT_HUNT "\xef\x8a\x88"	// U+f288
#define ICON_FA_PUSHED "\xef\x8f\xa1"	// U+f3e1
#define ICON_FA_PYTHON "\xef\x8f\xa2"	// U+f3e2
#define ICON_FA_QQ "\xef\x87\x96"	// U+f1d6
#define ICON_FA_QUINSCAPE "\xef\x91\x99"	// U+f459
#define ICON_FA_QUORA "\xef\x8b\x84"	// U+f2c4
#define ICON_FA_R_PROJECT "\xef\x93\xb7"	// U+f4f7
#define ICON_FA_RASPBERRY_PI "\xef\x9e\xbb"	// U+f7bb
#define ICON_FA_RAVELRY "\xef\x8b\x99"	// U+f2d9
#define ICON_FA_REACT "\xef\x90\x9b"	// U+f41b
#define ICON_FA_REACTEUROPE "\xef\x9d\x9d"	// U+f75d
#define ICON_FA_README "\xef\x93\x95"	// U+f4d5
#define ICON_FA_REBEL "\xef\x87\x90"	// U+f1d0
#define ICON_FA_RED_RIVER "\xef\x8f\xa3"	// U+f3e3
#define ICON_FA_REDDIT "\xef\x86\xa1"	// U+f1a1
#define ICON_FA_REDDIT_ALIEN "\xef\x8a\x81"	// U+f281
#define ICON_FA_REDHAT "\xef\x9e\xbc"	// U+f7bc
#define ICON_FA_RENREN "\xef\x86\x8b"	// U+f18b
#define ICON_FA_REPLYD "\xef\x8f\xa6"	// U+f3e6
#define ICON_FA_RESEARCHGATE "\xef\x93\xb8"	// U+f4f8
#define ICON_FA_RESOLVING "\xef\x8f\xa7"	// U+f3e7
#define ICON_FA_REV "\xef\x96\xb2"	// U+f5b2
#define ICON_FA_ROCKETCHAT "\xef\x8f\xa8"	// U+f3e8
#define ICON_FA_ROCKRMS "\xef\x8f\xa9"	// U+f3e9
#define ICON_FA_RUST "\xee\x81\xba"	// U+e07a
#define ICON_FA_SAFARI "\xef\x89\xa7"	// U+f267
#define ICON_FA_SALESFORCE "\xef\xa0\xbb"	// U+f83b
#define ICON_FA_SASS "\xef\x90\x9e"	// U+f41e
#define ICON_FA_SCHLIX "\xef\x8f\xaa"	// U+f3ea
#define ICON_FA_SCREENPAL "\xee\x95\xb0"	// U+e570
#define ICON_FA_SCRIBD "\xef\x8a\x8a"	// U+f28a
#define ICON_FA_SEARCHENGIN "\xef\x8f\xab"	// U+f3eb
#define ICON_FA_SELLCAST "\xef\x8b\x9a"	// U+f2da
#define ICON_FA_SELLSY "\xef\x88\x93"	// U+f213
#define ICON_FA_SERVICESTACK "\xef\x8f\xac"	// U+f3ec
#define ICON_FA_SHIRTSINBULK "\xef\x88\x94"	// U+f214
#define ICON_FA_SHOPIFY "\xee\x81\x97"	// U+e057
#define ICON_FA_SHOPWARE "\xef\x96\xb5"	// U+f5b5
#define ICON_FA_SIMPLYBUILT "\xef\x88\x95"	// U+f215
#define ICON_FA_SISTRIX "\xef\x8f\xae"	// U+f3ee
#define ICON_FA_SITH "\xef\x94\x92"	// U+f512
#define ICON_FA_SITROX "\xee\x91\x8a"	// U+e44a
#define ICON_FA_SKETCH "\xef\x9f\x86"	// U+f7c6
#define ICON_FA_SKYATLAS "\xef\x88\x96"	// U+f216
#define ICON_FA_SKYPE "\xef\x85\xbe"	// U+f17e
#define ICON_FA_SLACK "\xef\x86\x98"	// U+f198
#define ICON_FA_SLIDESHARE "\xef\x87\xa7"	// U+f1e7
#define ICON_FA_SNAPCHAT "\xef\x8a\xab"	// U+f2ab
#define ICON_FA_SOUNDCLOUD "\xef\x86\xbe"	// U+f1be
#define ICON_FA_SOURCETREE "\xef\x9f\x93"	// U+f7d3
#define ICON_FA_SPACE_AWESOME "\xee\x96\xac"	// U+e5ac
#define ICON_FA_SPEAKAP "\xef\x8f\xb3"	// U+f3f3
#define ICON_FA_SPEAKER_DECK "\xef\xa0\xbc"	// U+f83c
#define ICON_FA_SPOTIFY "\xef\x86\xbc"	// U+f1bc
#define ICON_FA_SQUARE_BEHANCE "\xef\x86\xb5"	// U+f1b5
#define ICON_FA_SQUARE_DRIBBBLE "\xef\x8e\x97"	// U+f397
#define ICON_FA_SQUARE_FACEBOOK "\xef\x82\x82"	// U+f082
#define ICON_FA_SQUARE_FONT_AWESOME "\xee\x96\xad"	// U+e5ad
#define ICON_FA_SQUARE_FONT_AWESOME_STROKE "\xef\x8d\x9c"	// U+f35c
#define ICON_FA_SQUARE_GIT "\xef\x87\x92"	// U+f1d2
#define ICON_FA_SQUARE_GITHUB "\xef\x82\x92"	// U+f092
#define ICON_FA_SQUARE_GITLAB "\xee\x96\xae"	// U+e5ae
#define ICON_FA_SQUARE_GOOGLE_PLUS "\xef\x83\x94"	// U+f0d4
#define ICON_FA_SQUARE_HACKER_NEWS "\xef\x8e\xaf"	// U+f3af
#define ICON_FA_SQUARE_INSTAGRAM "\xee\x81\x95"	// U+e055
#define ICON_FA_SQUARE_JS "\xef\x8e\xb9"	// U+f3b9
#define ICON_FA_SQUARE_LASTFM "\xef\x88\x83"	// U+f203
#define ICON_FA_SQUARE_ODNOKLASSNIKI "\xef\x89\xa4"	// U+f264
#define ICON_FA_SQUARE_PIED_PIPER "\xee\x80\x9e"	// U+e01e
#define ICON_FA_SQUARE_PINTEREST "\xef\x83\x93"	// U+f0d3
#define ICON_FA_SQUARE_REDDIT "\xef\x86\xa2"	// U+f1a2
#define ICON_FA_SQUARE_SNAPCHAT "\xef\x8a\xad"	// U+f2ad
#define ICON_FA_SQUARE_STEAM "\xef\x86\xb7"	// U+f1b7
#define ICON_FA_SQUARE_THREADS "\xee\x98\x99"	// U+e619
#define ICON_FA_SQUARE_TUMBLR "\xef\x85\xb4"	// U+f174
#define ICON_FA_SQUARE_TWITTER "\xef\x82\x81"	// U+f081
#define ICON_FA_SQUARE_VIADEO "\xef\x8a\xaa"	// U+f2aa
#define ICON_FA_SQUARE_VIMEO "\xef\x86\x94"	// U+f194
#define ICON_FA_SQUARE_WHATSAPP "\xef\x90\x8c"	// U+f40c
#define ICON_FA_SQUARE_X_TWITTER "\xee\x98\x9a"	// U+e61a
#define ICON_FA_SQUARE_XING "\xef\x85\xa9"	// U+f169
#define ICON_FA_SQUARE_YOUTUBE "\xef\x90\xb1"	// U+f431
#define ICON_FA_SQUARESPACE "\xef\x96\xbe"	// U+f5be
#define ICON_FA_STACK_EXCHANGE "\xef\x86\x8d"	// U+f18d
#define ICON_FA_STACK_OVERFLOW "\xef\x85\xac"	// U+f16c
#define ICON_FA_STACKPATH "\xef\xa1\x82"	// U+f842
#define ICON_FA_STAYLINKED "\xef\x8f\xb5"	// U+f3f5
#define ICON_FA_STEAM "\xef\x86\xb6"	// U+f1b6
#define ICON_FA_STEAM_SYMBOL "\xef\x8f\xb6"	// U+f3f6
#define ICON_FA_STICKER_MULE "\xef\x8f\xb7"	// U+f3f7
#define ICON_FA_STRAVA "\xef\x90\xa8"	// U+f428
#define ICON_FA_STRIPE "\xef\x90\xa9"	// U+f429
#define ICON_FA_STRIPE_S "\xef\x90\xaa"	// U+f42a
#define ICON_FA_STUBBER "\xee\x97\x87"	// U+e5c7
#define ICON_FA_STUDIOVINARI "\xef\x8f\xb8"	// U+f3f8
#define ICON_FA_STUMBLEUPON "\xef\x86\xa4"	// U+f1a4
#define ICON_FA_STUMBLEUPON_CIRCLE "\xef\x86\xa3"	// U+f1a3
#define ICON_FA_SUPERPOWERS "\xef\x8b\x9d"	// U+f2dd
#define ICON_FA_SUPPLE "\xef\x8f\xb9"	// U+f3f9
#define ICON_FA_SUSE "\xef\x9f\x96"	// U+f7d6
#define ICON_FA_SWIFT "\xef\xa3\xa1"	// U+f8e1
#define ICON_FA_SYMFONY "\xef\xa0\xbd"	// U+f83d
#define ICON_FA_TEAMSPEAK "\xef\x93\xb9"	// U+f4f9
#define ICON_FA_TELEGRAM "\xef\x8b\x86"	// U+f2c6
#define ICON_FA_TENCENT_WEIBO "\xef\x87\x95"	// U+f1d5
#define ICON_FA_THE_RED_YETI "\xef\x9a\x9d"	// U+f69d
#define ICON_FA_THEMECO "\xef\x97\x86"	// U+f5c6
#define ICON_FA_THEMEISLE "\xef\x8a\xb2"	// U+f2b2
#define ICON_FA_THINK_PEAKS "\xef\x9c\xb1"	// U+f731
#define ICON_FA_THREADS "\xee\x98\x98"	// U+e618
#define ICON_FA_TIKTOK "\xee\x81\xbb"	// U+e07b
#define ICON_FA_TRADE_FEDERATION "\xef\x94\x93"	// U+f513
#define ICON_FA_TRELLO "\xef\x86\x81"	// U+f181
#define ICON_FA_TUMBLR "\xef\x85\xb3"	// U+f173
#define ICON_FA_TWITCH "\xef\x87\xa8"	// U+f1e8
#define ICON_FA_TWITTER "\xef\x82\x99"	// U+f099
#define ICON_FA_TYPO3 "\xef\x90\xab"	// U+f42b
#define ICON_FA_UBER "\xef\x90\x82"	// U+f402
#define ICON_FA_UBUNTU "\xef\x9f\x9f"	// U+f7df
#define ICON_FA_UIKIT "\xef\x90\x83"	// U+f403
#define ICON_FA_UMBRACO "\xef\xa3\xa8"	// U+f8e8
#define ICON_FA_UNCHARTED "\xee\x82\x84"	// U+e084
#define ICON_FA_UNIREGISTRY "\xef\x90\x84"	// U+f404
#define ICON_FA_UNITY "\xee\x81\x89"	// U+e049
#define ICON_FA_UNSPLASH "\xee\x81\xbc"	// U+e07c
#define ICON_FA_UNTAPPD "\xef\x90\x85"	// U+f405
#define ICON_FA_UPS "\xef\x9f\xa0"	// U+f7e0
#define ICON_FA_USB "\xef\x8a\x87"	// U+f287
#define ICON_FA_USPS "\xef\x9f\xa1"	// U+f7e1
#define ICON_FA_USSUNNAH "\xef\x90\x87"	// U+f407
#define ICON_FA_VAADIN "\xef\x90\x88"	// U+f408
#define ICON_FA_VIACOIN "\xef\x88\xb7"	// U+f237
#define ICON_FA_VIADEO "\xef\x8a\xa9"	// U+f2a9
#define ICON_FA_VIBER "\xef\x90\x89"	// U+f409
#define ICON_FA_VIMEO "\xef\x90\x8a"	// U+f40a
#define ICON_FA_VIMEO_V "\xef\x89\xbd"	// U+f27d
#define ICON_FA_VINE "\xef\x87\x8a"	// U+f1ca
#define ICON_FA_VK "\xef\x86\x89"	// U+f189
#define ICON_FA_VNV "\xef\x90\x8b"	// U+f40b
#define ICON_FA_VUEJS "\xef\x90\x9f"	// U+f41f
#define ICON_FA_WATCHMAN_MONITORING "\xee\x82\x87"	// U+e087
#define ICON_FA_WAZE "\xef\xa0\xbf"	// U+f83f
#define ICON_FA_WEEBLY "\xef\x97\x8c"	// U+f5cc
#define ICON_FA_WEIBO "\xef\x86\x8a"	// U+f18a
#define ICON_FA_WEIXIN "\xef\x87\x97"	// U+f1d7
#define ICON_FA_WHATSAPP "\xef\x88\xb2"	// U+f232
#define ICON_FA_WHMCS "\xef\x90\x8d"	// U+f40d
#define ICON_FA_WIKIPEDIA_W "\xef\x89\xa6"	// U+f266
#define ICON_FA_WINDOWS "\xef\x85\xba"	// U+f17a
#define ICON_FA_WIRSINDHANDWERK "\xee\x8b\x90"	// U+e2d0
#define ICON_FA_WIX "\xef\x97\x8f"	// U+f5cf
#define ICON_FA_WIZARDS_OF_THE_COAST "\xef\x9c\xb0"	// U+f730
#define ICON_FA_WODU "\xee\x82\x88"	// U+e088
#define ICON_FA_WOLF_PACK_BATTALION "\xef\x94\x94"	// U+f514
#define ICON_FA_WORDPRESS "\xef\x86\x9a"	// U+f19a
#define ICON_FA_WORDPRESS_SIMPLE "\xef\x90\x91"	// U+f411
#define ICON_FA_WPBEGINNER "\xef\x8a\x97"	// U+f297
#define ICON_FA_WPEXPLORER "\xef\x8b\x9e"	// U+f2de
#define ICON_FA_WPFORMS "\xef\x8a\x98"	// U+f298
#define ICON_FA_WPRESSR "\xef\x8f\xa4"	// U+f3e4
#define ICON_FA_X_TWITTER "\xee\x98\x9b"	// U+e61b
#define ICON_FA_XBOX "\xef\x90\x92"	// U+f412
#define ICON_FA_XING "\xef\x85\xa8"	// U+f168
#define ICON_FA_Y_COMBINATOR "\xef\x88\xbb"	// U+f23b
#define ICON_FA_YAHOO "\xef\x86\x9e"	// U+f19e
#define ICON_FA_YAMMER "\xef\xa1\x80"	// U+f840
#define ICON_FA_YANDEX "\xef\x90\x93"	// U+f413
#define ICON_FA_YANDEX_INTERNATIONAL "\xef\x90\x94"	// U+f414
#define ICON_FA_YARN "\xef\x9f\xa3"	// U+f7e3
#define ICON_FA_YELP "\xef\x87\xa9"	// U+f1e9
#define ICON_FA_YOAST "\xef\x8a\xb1"	// U+f2b1
#define ICON_FA_YOUTUBE "\xef\x85\xa7"	// U+f167
#define ICON_FA_ZHIHU "\xef\x98\xbf"	// U+f63f

static const ImWchar S_A6B_Icon_Range[] =
{
	ICON_MIN_FAB,
#ifdef IMGUI_USE_WCHAR32            // ImWchar [configurable type: override in imconfig.h with '#define IMGUI_USE_WCHAR32' to support Unicode planes 1-16]
	ICON_MAX_FAB,
#else
	ICON_MAX_16_FAB,
#endif
	0
};

namespace IconsFontAwesome6Brands
{
	static void ImGuiDrawAllIcons()
	{
		ImGui::Text("Awesome 6 Brands Icons");
		ImGui::Text(ICON_FA_42_GROUP " || ICON_FA_42_GROUP");
		ImGui::Text(ICON_FA_500PX " || ICON_FA_500PX");
		ImGui::Text(ICON_FA_ACCESSIBLE_ICON " || ICON_FA_ACCESSIBLE_ICON");
		ImGui::Text(ICON_FA_ACCUSOFT " || ICON_FA_ACCUSOFT");
		ImGui::Text(ICON_FA_ADN " || ICON_FA_ADN");
		ImGui::Text(ICON_FA_ADVERSAL " || ICON_FA_ADVERSAL");
		ImGui::Text(ICON_FA_AFFILIATETHEME " || ICON_FA_AFFILIATETHEME");
		ImGui::Text(ICON_FA_AIRBNB " || ICON_FA_AIRBNB");
		ImGui::Text(ICON_FA_ALGOLIA " || ICON_FA_ALGOLIA");
		ImGui::Text(ICON_FA_ALIPAY " || ICON_FA_ALIPAY");
		ImGui::Text(ICON_FA_AMAZON " || ICON_FA_AMAZON");
		ImGui::Text(ICON_FA_AMAZON_PAY " || ICON_FA_AMAZON_PAY");
		ImGui::Text(ICON_FA_AMILIA " || ICON_FA_AMILIA");
		ImGui::Text(ICON_FA_ANDROID " || ICON_FA_ANDROID");
		ImGui::Text(ICON_FA_ANGELLIST " || ICON_FA_ANGELLIST");
		ImGui::Text(ICON_FA_ANGRYCREATIVE " || ICON_FA_ANGRYCREATIVE");
		ImGui::Text(ICON_FA_ANGULAR " || ICON_FA_ANGULAR");
		ImGui::Text(ICON_FA_APP_STORE " || ICON_FA_APP_STORE");
		ImGui::Text(ICON_FA_APP_STORE_IOS " || ICON_FA_APP_STORE_IOS");
		ImGui::Text(ICON_FA_APPER " || ICON_FA_APPER");
		ImGui::Text(ICON_FA_APPLE " || ICON_FA_APPLE");
		ImGui::Text(ICON_FA_APPLE_PAY " || ICON_FA_APPLE_PAY");
		ImGui::Text(ICON_FA_ARTSTATION " || ICON_FA_ARTSTATION");
		ImGui::Text(ICON_FA_ASYMMETRIK " || ICON_FA_ASYMMETRIK");
		ImGui::Text(ICON_FA_ATLASSIAN " || ICON_FA_ATLASSIAN");
		ImGui::Text(ICON_FA_AUDIBLE " || ICON_FA_AUDIBLE");
		ImGui::Text(ICON_FA_AUTOPREFIXER " || ICON_FA_AUTOPREFIXER");
		ImGui::Text(ICON_FA_AVIANEX " || ICON_FA_AVIANEX");
		ImGui::Text(ICON_FA_AVIATO " || ICON_FA_AVIATO");
		ImGui::Text(ICON_FA_AWS " || ICON_FA_AWS");
		ImGui::Text(ICON_FA_BANDCAMP " || ICON_FA_BANDCAMP");
		ImGui::Text(ICON_FA_BATTLE_NET " || ICON_FA_BATTLE_NET");
		ImGui::Text(ICON_FA_BEHANCE " || ICON_FA_BEHANCE");
		ImGui::Text(ICON_FA_BILIBILI " || ICON_FA_BILIBILI");
		ImGui::Text(ICON_FA_BIMOBJECT " || ICON_FA_BIMOBJECT");
		ImGui::Text(ICON_FA_BITBUCKET " || ICON_FA_BITBUCKET");
		ImGui::Text(ICON_FA_BITCOIN " || ICON_FA_BITCOIN");
		ImGui::Text(ICON_FA_BITY " || ICON_FA_BITY");
		ImGui::Text(ICON_FA_BLACK_TIE " || ICON_FA_BLACK_TIE");
		ImGui::Text(ICON_FA_BLACKBERRY " || ICON_FA_BLACKBERRY");
		ImGui::Text(ICON_FA_BLOGGER " || ICON_FA_BLOGGER");
		ImGui::Text(ICON_FA_BLOGGER_B " || ICON_FA_BLOGGER_B");
		ImGui::Text(ICON_FA_BLUETOOTH " || ICON_FA_BLUETOOTH");
		ImGui::Text(ICON_FA_BLUETOOTH_B " || ICON_FA_BLUETOOTH_B");
		ImGui::Text(ICON_FA_BOOTSTRAP " || ICON_FA_BOOTSTRAP");
		ImGui::Text(ICON_FA_BOTS " || ICON_FA_BOTS");
		ImGui::Text(ICON_FA_BTC " || ICON_FA_BTC");
		ImGui::Text(ICON_FA_BUFFER " || ICON_FA_BUFFER");
		ImGui::Text(ICON_FA_BUROMOBELEXPERTE " || ICON_FA_BUROMOBELEXPERTE");
		ImGui::Text(ICON_FA_BUY_N_LARGE " || ICON_FA_BUY_N_LARGE");
		ImGui::Text(ICON_FA_BUYSELLADS " || ICON_FA_BUYSELLADS");
		ImGui::Text(ICON_FA_CANADIAN_MAPLE_LEAF " || ICON_FA_CANADIAN_MAPLE_LEAF");
		ImGui::Text(ICON_FA_CC_AMAZON_PAY " || ICON_FA_CC_AMAZON_PAY");
		ImGui::Text(ICON_FA_CC_AMEX " || ICON_FA_CC_AMEX");
		ImGui::Text(ICON_FA_CC_APPLE_PAY " || ICON_FA_CC_APPLE_PAY");
		ImGui::Text(ICON_FA_CC_DINERS_CLUB " || ICON_FA_CC_DINERS_CLUB");
		ImGui::Text(ICON_FA_CC_DISCOVER " || ICON_FA_CC_DISCOVER");
		ImGui::Text(ICON_FA_CC_JCB " || ICON_FA_CC_JCB");
		ImGui::Text(ICON_FA_CC_MASTERCARD " || ICON_FA_CC_MASTERCARD");
		ImGui::Text(ICON_FA_CC_PAYPAL " || ICON_FA_CC_PAYPAL");
		ImGui::Text(ICON_FA_CC_STRIPE " || ICON_FA_CC_STRIPE");
		ImGui::Text(ICON_FA_CC_VISA " || ICON_FA_CC_VISA");
		ImGui::Text(ICON_FA_CENTERCODE " || ICON_FA_CENTERCODE");
		ImGui::Text(ICON_FA_CENTOS " || ICON_FA_CENTOS");
		ImGui::Text(ICON_FA_CHROME " || ICON_FA_CHROME");
		ImGui::Text(ICON_FA_CHROMECAST " || ICON_FA_CHROMECAST");
		ImGui::Text(ICON_FA_CLOUDFLARE " || ICON_FA_CLOUDFLARE");
		ImGui::Text(ICON_FA_CLOUDSCALE " || ICON_FA_CLOUDSCALE");
		ImGui::Text(ICON_FA_CLOUDSMITH " || ICON_FA_CLOUDSMITH");
		ImGui::Text(ICON_FA_CLOUDVERSIFY " || ICON_FA_CLOUDVERSIFY");
		ImGui::Text(ICON_FA_CMPLID " || ICON_FA_CMPLID");
		ImGui::Text(ICON_FA_CODEPEN " || ICON_FA_CODEPEN");
		ImGui::Text(ICON_FA_CODIEPIE " || ICON_FA_CODIEPIE");
		ImGui::Text(ICON_FA_CONFLUENCE " || ICON_FA_CONFLUENCE");
		ImGui::Text(ICON_FA_CONNECTDEVELOP " || ICON_FA_CONNECTDEVELOP");
		ImGui::Text(ICON_FA_CONTAO " || ICON_FA_CONTAO");
		ImGui::Text(ICON_FA_COTTON_BUREAU " || ICON_FA_COTTON_BUREAU");
		ImGui::Text(ICON_FA_CPANEL " || ICON_FA_CPANEL");
		ImGui::Text(ICON_FA_CREATIVE_COMMONS " || ICON_FA_CREATIVE_COMMONS");
		ImGui::Text(ICON_FA_CREATIVE_COMMONS_BY " || ICON_FA_CREATIVE_COMMONS_BY");
		ImGui::Text(ICON_FA_CREATIVE_COMMONS_NC " || ICON_FA_CREATIVE_COMMONS_NC");
		ImGui::Text(ICON_FA_CREATIVE_COMMONS_NC_EU " || ICON_FA_CREATIVE_COMMONS_NC_EU");
		ImGui::Text(ICON_FA_CREATIVE_COMMONS_NC_JP " || ICON_FA_CREATIVE_COMMONS_NC_JP");
		ImGui::Text(ICON_FA_CREATIVE_COMMONS_ND " || ICON_FA_CREATIVE_COMMONS_ND");
		ImGui::Text(ICON_FA_CREATIVE_COMMONS_PD " || ICON_FA_CREATIVE_COMMONS_PD");
		ImGui::Text(ICON_FA_CREATIVE_COMMONS_PD_ALT " || ICON_FA_CREATIVE_COMMONS_PD_ALT");
		ImGui::Text(ICON_FA_CREATIVE_COMMONS_REMIX " || ICON_FA_CREATIVE_COMMONS_REMIX");
		ImGui::Text(ICON_FA_CREATIVE_COMMONS_SA " || ICON_FA_CREATIVE_COMMONS_SA");
		ImGui::Text(ICON_FA_CREATIVE_COMMONS_SAMPLING " || ICON_FA_CREATIVE_COMMONS_SAMPLING");
		ImGui::Text(ICON_FA_CREATIVE_COMMONS_SAMPLING_PLUS " || ICON_FA_CREATIVE_COMMONS_SAMPLING_PLUS");
		ImGui::Text(ICON_FA_CREATIVE_COMMONS_SHARE " || ICON_FA_CREATIVE_COMMONS_SHARE");
		ImGui::Text(ICON_FA_CREATIVE_COMMONS_ZERO " || ICON_FA_CREATIVE_COMMONS_ZERO");
		ImGui::Text(ICON_FA_CRITICAL_ROLE " || ICON_FA_CRITICAL_ROLE");
		ImGui::Text(ICON_FA_CSS3 " || ICON_FA_CSS3");
		ImGui::Text(ICON_FA_CSS3_ALT " || ICON_FA_CSS3_ALT");
		ImGui::Text(ICON_FA_CUTTLEFISH " || ICON_FA_CUTTLEFISH");
		ImGui::Text(ICON_FA_D_AND_D " || ICON_FA_D_AND_D");
		ImGui::Text(ICON_FA_D_AND_D_BEYOND " || ICON_FA_D_AND_D_BEYOND");
		ImGui::Text(ICON_FA_DAILYMOTION " || ICON_FA_DAILYMOTION");
		ImGui::Text(ICON_FA_DASHCUBE " || ICON_FA_DASHCUBE");
		ImGui::Text(ICON_FA_DEBIAN " || ICON_FA_DEBIAN");
		ImGui::Text(ICON_FA_DEEZER " || ICON_FA_DEEZER");
		ImGui::Text(ICON_FA_DELICIOUS " || ICON_FA_DELICIOUS");
		ImGui::Text(ICON_FA_DEPLOYDOG " || ICON_FA_DEPLOYDOG");
		ImGui::Text(ICON_FA_DESKPRO " || ICON_FA_DESKPRO");
		ImGui::Text(ICON_FA_DEV " || ICON_FA_DEV");
		ImGui::Text(ICON_FA_DEVIANTART " || ICON_FA_DEVIANTART");
		ImGui::Text(ICON_FA_DHL " || ICON_FA_DHL");
		ImGui::Text(ICON_FA_DIASPORA " || ICON_FA_DIASPORA");
		ImGui::Text(ICON_FA_DIGG " || ICON_FA_DIGG");
		ImGui::Text(ICON_FA_DIGITAL_OCEAN " || ICON_FA_DIGITAL_OCEAN");
		ImGui::Text(ICON_FA_DISCORD " || ICON_FA_DISCORD");
		ImGui::Text(ICON_FA_DISCOURSE " || ICON_FA_DISCOURSE");
		ImGui::Text(ICON_FA_DOCHUB " || ICON_FA_DOCHUB");
		ImGui::Text(ICON_FA_DOCKER " || ICON_FA_DOCKER");
		ImGui::Text(ICON_FA_DRAFT2DIGITAL " || ICON_FA_DRAFT2DIGITAL");
		ImGui::Text(ICON_FA_DRIBBBLE " || ICON_FA_DRIBBBLE");
		ImGui::Text(ICON_FA_DROPBOX " || ICON_FA_DROPBOX");
		ImGui::Text(ICON_FA_DRUPAL " || ICON_FA_DRUPAL");
		ImGui::Text(ICON_FA_DYALOG " || ICON_FA_DYALOG");
		ImGui::Text(ICON_FA_EARLYBIRDS " || ICON_FA_EARLYBIRDS");
		ImGui::Text(ICON_FA_EBAY " || ICON_FA_EBAY");
		ImGui::Text(ICON_FA_EDGE " || ICON_FA_EDGE");
		ImGui::Text(ICON_FA_EDGE_LEGACY " || ICON_FA_EDGE_LEGACY");
		ImGui::Text(ICON_FA_ELEMENTOR " || ICON_FA_ELEMENTOR");
		ImGui::Text(ICON_FA_ELLO " || ICON_FA_ELLO");
		ImGui::Text(ICON_FA_EMBER " || ICON_FA_EMBER");
		ImGui::Text(ICON_FA_EMPIRE " || ICON_FA_EMPIRE");
		ImGui::Text(ICON_FA_ENVIRA " || ICON_FA_ENVIRA");
		ImGui::Text(ICON_FA_ERLANG " || ICON_FA_ERLANG");
		ImGui::Text(ICON_FA_ETHEREUM " || ICON_FA_ETHEREUM");
		ImGui::Text(ICON_FA_ETSY " || ICON_FA_ETSY");
		ImGui::Text(ICON_FA_EVERNOTE " || ICON_FA_EVERNOTE");
		ImGui::Text(ICON_FA_EXPEDITEDSSL " || ICON_FA_EXPEDITEDSSL");
		ImGui::Text(ICON_FA_FACEBOOK " || ICON_FA_FACEBOOK");
		ImGui::Text(ICON_FA_FACEBOOK_F " || ICON_FA_FACEBOOK_F");
		ImGui::Text(ICON_FA_FACEBOOK_MESSENGER " || ICON_FA_FACEBOOK_MESSENGER");
		ImGui::Text(ICON_FA_FANTASY_FLIGHT_GAMES " || ICON_FA_FANTASY_FLIGHT_GAMES");
		ImGui::Text(ICON_FA_FEDEX " || ICON_FA_FEDEX");
		ImGui::Text(ICON_FA_FEDORA " || ICON_FA_FEDORA");
		ImGui::Text(ICON_FA_FIGMA " || ICON_FA_FIGMA");
		ImGui::Text(ICON_FA_FIREFOX " || ICON_FA_FIREFOX");
		ImGui::Text(ICON_FA_FIREFOX_BROWSER " || ICON_FA_FIREFOX_BROWSER");
		ImGui::Text(ICON_FA_FIRST_ORDER " || ICON_FA_FIRST_ORDER");
		ImGui::Text(ICON_FA_FIRST_ORDER_ALT " || ICON_FA_FIRST_ORDER_ALT");
		ImGui::Text(ICON_FA_FIRSTDRAFT " || ICON_FA_FIRSTDRAFT");
		ImGui::Text(ICON_FA_FLICKR " || ICON_FA_FLICKR");
		ImGui::Text(ICON_FA_FLIPBOARD " || ICON_FA_FLIPBOARD");
		ImGui::Text(ICON_FA_FLY " || ICON_FA_FLY");
		ImGui::Text(ICON_FA_FONT_AWESOME " || ICON_FA_FONT_AWESOME");
		ImGui::Text(ICON_FA_FONTICONS " || ICON_FA_FONTICONS");
		ImGui::Text(ICON_FA_FONTICONS_FI " || ICON_FA_FONTICONS_FI");
		ImGui::Text(ICON_FA_FORT_AWESOME " || ICON_FA_FORT_AWESOME");
		ImGui::Text(ICON_FA_FORT_AWESOME_ALT " || ICON_FA_FORT_AWESOME_ALT");
		ImGui::Text(ICON_FA_FORUMBEE " || ICON_FA_FORUMBEE");
		ImGui::Text(ICON_FA_FOURSQUARE " || ICON_FA_FOURSQUARE");
		ImGui::Text(ICON_FA_FREE_CODE_CAMP " || ICON_FA_FREE_CODE_CAMP");
		ImGui::Text(ICON_FA_FREEBSD " || ICON_FA_FREEBSD");
		ImGui::Text(ICON_FA_FULCRUM " || ICON_FA_FULCRUM");
		ImGui::Text(ICON_FA_GALACTIC_REPUBLIC " || ICON_FA_GALACTIC_REPUBLIC");
		ImGui::Text(ICON_FA_GALACTIC_SENATE " || ICON_FA_GALACTIC_SENATE");
		ImGui::Text(ICON_FA_GET_POCKET " || ICON_FA_GET_POCKET");
		ImGui::Text(ICON_FA_GG " || ICON_FA_GG");
		ImGui::Text(ICON_FA_GG_CIRCLE " || ICON_FA_GG_CIRCLE");
		ImGui::Text(ICON_FA_GIT " || ICON_FA_GIT");
		ImGui::Text(ICON_FA_GIT_ALT " || ICON_FA_GIT_ALT");
		ImGui::Text(ICON_FA_GITHUB " || ICON_FA_GITHUB");
		ImGui::Text(ICON_FA_GITHUB_ALT " || ICON_FA_GITHUB_ALT");
		ImGui::Text(ICON_FA_GITKRAKEN " || ICON_FA_GITKRAKEN");
		ImGui::Text(ICON_FA_GITLAB " || ICON_FA_GITLAB");
		ImGui::Text(ICON_FA_GITTER " || ICON_FA_GITTER");
		ImGui::Text(ICON_FA_GLIDE " || ICON_FA_GLIDE");
		ImGui::Text(ICON_FA_GLIDE_G " || ICON_FA_GLIDE_G");
		ImGui::Text(ICON_FA_GOFORE " || ICON_FA_GOFORE");
		ImGui::Text(ICON_FA_GOLANG " || ICON_FA_GOLANG");
		ImGui::Text(ICON_FA_GOODREADS " || ICON_FA_GOODREADS");
		ImGui::Text(ICON_FA_GOODREADS_G " || ICON_FA_GOODREADS_G");
		ImGui::Text(ICON_FA_GOOGLE " || ICON_FA_GOOGLE");
		ImGui::Text(ICON_FA_GOOGLE_DRIVE " || ICON_FA_GOOGLE_DRIVE");
		ImGui::Text(ICON_FA_GOOGLE_PAY " || ICON_FA_GOOGLE_PAY");
		ImGui::Text(ICON_FA_GOOGLE_PLAY " || ICON_FA_GOOGLE_PLAY");
		ImGui::Text(ICON_FA_GOOGLE_PLUS " || ICON_FA_GOOGLE_PLUS");
		ImGui::Text(ICON_FA_GOOGLE_PLUS_G " || ICON_FA_GOOGLE_PLUS_G");
		ImGui::Text(ICON_FA_GOOGLE_WALLET " || ICON_FA_GOOGLE_WALLET");
		ImGui::Text(ICON_FA_GRATIPAY " || ICON_FA_GRATIPAY");
		ImGui::Text(ICON_FA_GRAV " || ICON_FA_GRAV");
		ImGui::Text(ICON_FA_GRIPFIRE " || ICON_FA_GRIPFIRE");
		ImGui::Text(ICON_FA_GRUNT " || ICON_FA_GRUNT");
		ImGui::Text(ICON_FA_GUILDED " || ICON_FA_GUILDED");
		ImGui::Text(ICON_FA_GULP " || ICON_FA_GULP");
		ImGui::Text(ICON_FA_HACKER_NEWS " || ICON_FA_HACKER_NEWS");
		ImGui::Text(ICON_FA_HACKERRANK " || ICON_FA_HACKERRANK");
		ImGui::Text(ICON_FA_HASHNODE " || ICON_FA_HASHNODE");
		ImGui::Text(ICON_FA_HIPS " || ICON_FA_HIPS");
		ImGui::Text(ICON_FA_HIRE_A_HELPER " || ICON_FA_HIRE_A_HELPER");
		ImGui::Text(ICON_FA_HIVE " || ICON_FA_HIVE");
		ImGui::Text(ICON_FA_HOOLI " || ICON_FA_HOOLI");
		ImGui::Text(ICON_FA_HORNBILL " || ICON_FA_HORNBILL");
		ImGui::Text(ICON_FA_HOTJAR " || ICON_FA_HOTJAR");
		ImGui::Text(ICON_FA_HOUZZ " || ICON_FA_HOUZZ");
		ImGui::Text(ICON_FA_HTML5 " || ICON_FA_HTML5");
		ImGui::Text(ICON_FA_HUBSPOT " || ICON_FA_HUBSPOT");
		ImGui::Text(ICON_FA_IDEAL " || ICON_FA_IDEAL");
		ImGui::Text(ICON_FA_IMDB " || ICON_FA_IMDB");
		ImGui::Text(ICON_FA_INSTAGRAM " || ICON_FA_INSTAGRAM");
		ImGui::Text(ICON_FA_INSTALOD " || ICON_FA_INSTALOD");
		ImGui::Text(ICON_FA_INTERCOM " || ICON_FA_INTERCOM");
		ImGui::Text(ICON_FA_INTERNET_EXPLORER " || ICON_FA_INTERNET_EXPLORER");
		ImGui::Text(ICON_FA_INVISION " || ICON_FA_INVISION");
		ImGui::Text(ICON_FA_IOXHOST " || ICON_FA_IOXHOST");
		ImGui::Text(ICON_FA_ITCH_IO " || ICON_FA_ITCH_IO");
		ImGui::Text(ICON_FA_ITUNES " || ICON_FA_ITUNES");
		ImGui::Text(ICON_FA_ITUNES_NOTE " || ICON_FA_ITUNES_NOTE");
		ImGui::Text(ICON_FA_JAVA " || ICON_FA_JAVA");
		ImGui::Text(ICON_FA_JEDI_ORDER " || ICON_FA_JEDI_ORDER");
		ImGui::Text(ICON_FA_JENKINS " || ICON_FA_JENKINS");
		ImGui::Text(ICON_FA_JIRA " || ICON_FA_JIRA");
		ImGui::Text(ICON_FA_JOGET " || ICON_FA_JOGET");
		ImGui::Text(ICON_FA_JOOMLA " || ICON_FA_JOOMLA");
		ImGui::Text(ICON_FA_JS " || ICON_FA_JS");
		ImGui::Text(ICON_FA_JSFIDDLE " || ICON_FA_JSFIDDLE");
		ImGui::Text(ICON_FA_KAGGLE " || ICON_FA_KAGGLE");
		ImGui::Text(ICON_FA_KEYBASE " || ICON_FA_KEYBASE");
		ImGui::Text(ICON_FA_KEYCDN " || ICON_FA_KEYCDN");
		ImGui::Text(ICON_FA_KICKSTARTER " || ICON_FA_KICKSTARTER");
		ImGui::Text(ICON_FA_KICKSTARTER_K " || ICON_FA_KICKSTARTER_K");
		ImGui::Text(ICON_FA_KORVUE " || ICON_FA_KORVUE");
		ImGui::Text(ICON_FA_LARAVEL " || ICON_FA_LARAVEL");
		ImGui::Text(ICON_FA_LASTFM " || ICON_FA_LASTFM");
		ImGui::Text(ICON_FA_LEANPUB " || ICON_FA_LEANPUB");
		ImGui::Text(ICON_FA_LESS " || ICON_FA_LESS");
		ImGui::Text(ICON_FA_LINE " || ICON_FA_LINE");
		ImGui::Text(ICON_FA_LINKEDIN " || ICON_FA_LINKEDIN");
		ImGui::Text(ICON_FA_LINKEDIN_IN " || ICON_FA_LINKEDIN_IN");
		ImGui::Text(ICON_FA_LINODE " || ICON_FA_LINODE");
		ImGui::Text(ICON_FA_LINUX " || ICON_FA_LINUX");
		ImGui::Text(ICON_FA_LYFT " || ICON_FA_LYFT");
		ImGui::Text(ICON_FA_MAGENTO " || ICON_FA_MAGENTO");
		ImGui::Text(ICON_FA_MAILCHIMP " || ICON_FA_MAILCHIMP");
		ImGui::Text(ICON_FA_MANDALORIAN " || ICON_FA_MANDALORIAN");
		ImGui::Text(ICON_FA_MARKDOWN " || ICON_FA_MARKDOWN");
		ImGui::Text(ICON_FA_MASTODON " || ICON_FA_MASTODON");
		ImGui::Text(ICON_FA_MAXCDN " || ICON_FA_MAXCDN");
		ImGui::Text(ICON_FA_MDB " || ICON_FA_MDB");
		ImGui::Text(ICON_FA_MEDAPPS " || ICON_FA_MEDAPPS");
		ImGui::Text(ICON_FA_MEDIUM " || ICON_FA_MEDIUM");
		ImGui::Text(ICON_FA_MEDRT " || ICON_FA_MEDRT");
		ImGui::Text(ICON_FA_MEETUP " || ICON_FA_MEETUP");
		ImGui::Text(ICON_FA_MEGAPORT " || ICON_FA_MEGAPORT");
		ImGui::Text(ICON_FA_MENDELEY " || ICON_FA_MENDELEY");
		ImGui::Text(ICON_FA_META " || ICON_FA_META");
		ImGui::Text(ICON_FA_MICROBLOG " || ICON_FA_MICROBLOG");
		ImGui::Text(ICON_FA_MICROSOFT " || ICON_FA_MICROSOFT");
		ImGui::Text(ICON_FA_MIX " || ICON_FA_MIX");
		ImGui::Text(ICON_FA_MIXCLOUD " || ICON_FA_MIXCLOUD");
		ImGui::Text(ICON_FA_MIXER " || ICON_FA_MIXER");
		ImGui::Text(ICON_FA_MIZUNI " || ICON_FA_MIZUNI");
		ImGui::Text(ICON_FA_MODX " || ICON_FA_MODX");
		ImGui::Text(ICON_FA_MONERO " || ICON_FA_MONERO");
		ImGui::Text(ICON_FA_NAPSTER " || ICON_FA_NAPSTER");
		ImGui::Text(ICON_FA_NEOS " || ICON_FA_NEOS");
		ImGui::Text(ICON_FA_NFC_DIRECTIONAL " || ICON_FA_NFC_DIRECTIONAL");
		ImGui::Text(ICON_FA_NFC_SYMBOL " || ICON_FA_NFC_SYMBOL");
		ImGui::Text(ICON_FA_NIMBLR " || ICON_FA_NIMBLR");
		ImGui::Text(ICON_FA_NODE " || ICON_FA_NODE");
		ImGui::Text(ICON_FA_NODE_JS " || ICON_FA_NODE_JS");
		ImGui::Text(ICON_FA_NPM " || ICON_FA_NPM");
		ImGui::Text(ICON_FA_NS8 " || ICON_FA_NS8");
		ImGui::Text(ICON_FA_NUTRITIONIX " || ICON_FA_NUTRITIONIX");
		ImGui::Text(ICON_FA_OCTOPUS_DEPLOY " || ICON_FA_OCTOPUS_DEPLOY");
		ImGui::Text(ICON_FA_ODNOKLASSNIKI " || ICON_FA_ODNOKLASSNIKI");
		ImGui::Text(ICON_FA_ODYSEE " || ICON_FA_ODYSEE");
		ImGui::Text(ICON_FA_OLD_REPUBLIC " || ICON_FA_OLD_REPUBLIC");
		ImGui::Text(ICON_FA_OPENCART " || ICON_FA_OPENCART");
		ImGui::Text(ICON_FA_OPENID " || ICON_FA_OPENID");
		ImGui::Text(ICON_FA_OPERA " || ICON_FA_OPERA");
		ImGui::Text(ICON_FA_OPTIN_MONSTER " || ICON_FA_OPTIN_MONSTER");
		ImGui::Text(ICON_FA_ORCID " || ICON_FA_ORCID");
		ImGui::Text(ICON_FA_OSI " || ICON_FA_OSI");
		ImGui::Text(ICON_FA_PADLET " || ICON_FA_PADLET");
		ImGui::Text(ICON_FA_PAGE4 " || ICON_FA_PAGE4");
		ImGui::Text(ICON_FA_PAGELINES " || ICON_FA_PAGELINES");
		ImGui::Text(ICON_FA_PALFED " || ICON_FA_PALFED");
		ImGui::Text(ICON_FA_PATREON " || ICON_FA_PATREON");
		ImGui::Text(ICON_FA_PAYPAL " || ICON_FA_PAYPAL");
		ImGui::Text(ICON_FA_PERBYTE " || ICON_FA_PERBYTE");
		ImGui::Text(ICON_FA_PERISCOPE " || ICON_FA_PERISCOPE");
		ImGui::Text(ICON_FA_PHABRICATOR " || ICON_FA_PHABRICATOR");
		ImGui::Text(ICON_FA_PHOENIX_FRAMEWORK " || ICON_FA_PHOENIX_FRAMEWORK");
		ImGui::Text(ICON_FA_PHOENIX_SQUADRON " || ICON_FA_PHOENIX_SQUADRON");
		ImGui::Text(ICON_FA_PHP " || ICON_FA_PHP");
		ImGui::Text(ICON_FA_PIED_PIPER " || ICON_FA_PIED_PIPER");
		ImGui::Text(ICON_FA_PIED_PIPER_ALT " || ICON_FA_PIED_PIPER_ALT");
		ImGui::Text(ICON_FA_PIED_PIPER_HAT " || ICON_FA_PIED_PIPER_HAT");
		ImGui::Text(ICON_FA_PIED_PIPER_PP " || ICON_FA_PIED_PIPER_PP");
		ImGui::Text(ICON_FA_PINTEREST " || ICON_FA_PINTEREST");
		ImGui::Text(ICON_FA_PINTEREST_P " || ICON_FA_PINTEREST_P");
		ImGui::Text(ICON_FA_PIX " || ICON_FA_PIX");
		ImGui::Text(ICON_FA_PLAYSTATION " || ICON_FA_PLAYSTATION");
		ImGui::Text(ICON_FA_PRODUCT_HUNT " || ICON_FA_PRODUCT_HUNT");
		ImGui::Text(ICON_FA_PUSHED " || ICON_FA_PUSHED");
		ImGui::Text(ICON_FA_PYTHON " || ICON_FA_PYTHON");
		ImGui::Text(ICON_FA_QQ " || ICON_FA_QQ");
		ImGui::Text(ICON_FA_QUINSCAPE " || ICON_FA_QUINSCAPE");
		ImGui::Text(ICON_FA_QUORA " || ICON_FA_QUORA");
		ImGui::Text(ICON_FA_R_PROJECT " || ICON_FA_R_PROJECT");
		ImGui::Text(ICON_FA_RASPBERRY_PI " || ICON_FA_RASPBERRY_PI");
		ImGui::Text(ICON_FA_RAVELRY " || ICON_FA_RAVELRY");
		ImGui::Text(ICON_FA_REACT " || ICON_FA_REACT");
		ImGui::Text(ICON_FA_REACTEUROPE " || ICON_FA_REACTEUROPE");
		ImGui::Text(ICON_FA_README " || ICON_FA_README");
		ImGui::Text(ICON_FA_REBEL " || ICON_FA_REBEL");
		ImGui::Text(ICON_FA_RED_RIVER " || ICON_FA_RED_RIVER");
		ImGui::Text(ICON_FA_REDDIT " || ICON_FA_REDDIT");
		ImGui::Text(ICON_FA_REDDIT_ALIEN " || ICON_FA_REDDIT_ALIEN");
		ImGui::Text(ICON_FA_REDHAT " || ICON_FA_REDHAT");
		ImGui::Text(ICON_FA_RENREN " || ICON_FA_RENREN");
		ImGui::Text(ICON_FA_REPLYD " || ICON_FA_REPLYD");
		ImGui::Text(ICON_FA_RESEARCHGATE " || ICON_FA_RESEARCHGATE");
		ImGui::Text(ICON_FA_RESOLVING " || ICON_FA_RESOLVING");
		ImGui::Text(ICON_FA_REV " || ICON_FA_REV");
		ImGui::Text(ICON_FA_ROCKETCHAT " || ICON_FA_ROCKETCHAT");
		ImGui::Text(ICON_FA_ROCKRMS " || ICON_FA_ROCKRMS");
		ImGui::Text(ICON_FA_RUST " || ICON_FA_RUST");
		ImGui::Text(ICON_FA_SAFARI " || ICON_FA_SAFARI");
		ImGui::Text(ICON_FA_SALESFORCE " || ICON_FA_SALESFORCE");
		ImGui::Text(ICON_FA_SASS " || ICON_FA_SASS");
		ImGui::Text(ICON_FA_SCHLIX " || ICON_FA_SCHLIX");
		ImGui::Text(ICON_FA_SCREENPAL " || ICON_FA_SCREENPAL");
		ImGui::Text(ICON_FA_SCRIBD " || ICON_FA_SCRIBD");
		ImGui::Text(ICON_FA_SEARCHENGIN " || ICON_FA_SEARCHENGIN");
		ImGui::Text(ICON_FA_SELLCAST " || ICON_FA_SELLCAST");
		ImGui::Text(ICON_FA_SELLSY " || ICON_FA_SELLSY");
		ImGui::Text(ICON_FA_SERVICESTACK " || ICON_FA_SERVICESTACK");
		ImGui::Text(ICON_FA_SHIRTSINBULK " || ICON_FA_SHIRTSINBULK");
		ImGui::Text(ICON_FA_SHOPIFY " || ICON_FA_SHOPIFY");
		ImGui::Text(ICON_FA_SHOPWARE " || ICON_FA_SHOPWARE");
		ImGui::Text(ICON_FA_SIMPLYBUILT " || ICON_FA_SIMPLYBUILT");
		ImGui::Text(ICON_FA_SISTRIX " || ICON_FA_SISTRIX");
		ImGui::Text(ICON_FA_SITH " || ICON_FA_SITH");
		ImGui::Text(ICON_FA_SITROX " || ICON_FA_SITROX");
		ImGui::Text(ICON_FA_SKETCH " || ICON_FA_SKETCH");
		ImGui::Text(ICON_FA_SKYATLAS " || ICON_FA_SKYATLAS");
		ImGui::Text(ICON_FA_SKYPE " || ICON_FA_SKYPE");
		ImGui::Text(ICON_FA_SLACK " || ICON_FA_SLACK");
		ImGui::Text(ICON_FA_SLIDESHARE " || ICON_FA_SLIDESHARE");
		ImGui::Text(ICON_FA_SNAPCHAT " || ICON_FA_SNAPCHAT");
		ImGui::Text(ICON_FA_SOUNDCLOUD " || ICON_FA_SOUNDCLOUD");
		ImGui::Text(ICON_FA_SOURCETREE " || ICON_FA_SOURCETREE");
		ImGui::Text(ICON_FA_SPACE_AWESOME " || ICON_FA_SPACE_AWESOME");
		ImGui::Text(ICON_FA_SPEAKAP " || ICON_FA_SPEAKAP");
		ImGui::Text(ICON_FA_SPEAKER_DECK " || ICON_FA_SPEAKER_DECK");
		ImGui::Text(ICON_FA_SPOTIFY " || ICON_FA_SPOTIFY");
		ImGui::Text(ICON_FA_SQUARE_BEHANCE " || ICON_FA_SQUARE_BEHANCE");
		ImGui::Text(ICON_FA_SQUARE_DRIBBBLE " || ICON_FA_SQUARE_DRIBBBLE");
		ImGui::Text(ICON_FA_SQUARE_FACEBOOK " || ICON_FA_SQUARE_FACEBOOK");
		ImGui::Text(ICON_FA_SQUARE_FONT_AWESOME " || ICON_FA_SQUARE_FONT_AWESOME");
		ImGui::Text(ICON_FA_SQUARE_FONT_AWESOME_STROKE " || ICON_FA_SQUARE_FONT_AWESOME_STROKE");
		ImGui::Text(ICON_FA_SQUARE_GIT " || ICON_FA_SQUARE_GIT");
		ImGui::Text(ICON_FA_SQUARE_GITHUB " || ICON_FA_SQUARE_GITHUB");
		ImGui::Text(ICON_FA_SQUARE_GITLAB " || ICON_FA_SQUARE_GITLAB");
		ImGui::Text(ICON_FA_SQUARE_GOOGLE_PLUS " || ICON_FA_SQUARE_GOOGLE_PLUS");
		ImGui::Text(ICON_FA_SQUARE_HACKER_NEWS " || ICON_FA_SQUARE_HACKER_NEWS");
		ImGui::Text(ICON_FA_SQUARE_INSTAGRAM " || ICON_FA_SQUARE_INSTAGRAM");
		ImGui::Text(ICON_FA_SQUARE_JS " || ICON_FA_SQUARE_JS");
		ImGui::Text(ICON_FA_SQUARE_LASTFM " || ICON_FA_SQUARE_LASTFM");
		ImGui::Text(ICON_FA_SQUARE_ODNOKLASSNIKI " || ICON_FA_SQUARE_ODNOKLASSNIKI");
		ImGui::Text(ICON_FA_SQUARE_PIED_PIPER " || ICON_FA_SQUARE_PIED_PIPER");
		ImGui::Text(ICON_FA_SQUARE_PINTEREST " || ICON_FA_SQUARE_PINTEREST");
		ImGui::Text(ICON_FA_SQUARE_REDDIT " || ICON_FA_SQUARE_REDDIT");
		ImGui::Text(ICON_FA_SQUARE_SNAPCHAT " || ICON_FA_SQUARE_SNAPCHAT");
		ImGui::Text(ICON_FA_SQUARE_STEAM " || ICON_FA_SQUARE_STEAM");
		ImGui::Text(ICON_FA_SQUARE_THREADS " || ICON_FA_SQUARE_THREADS");
		ImGui::Text(ICON_FA_SQUARE_TUMBLR " || ICON_FA_SQUARE_TUMBLR");
		ImGui::Text(ICON_FA_SQUARE_TWITTER " || ICON_FA_SQUARE_TWITTER");
		ImGui::Text(ICON_FA_SQUARE_VIADEO " || ICON_FA_SQUARE_VIADEO");
		ImGui::Text(ICON_FA_SQUARE_VIMEO " || ICON_FA_SQUARE_VIMEO");
		ImGui::Text(ICON_FA_SQUARE_WHATSAPP " || ICON_FA_SQUARE_WHATSAPP");
		ImGui::Text(ICON_FA_SQUARE_X_TWITTER " || ICON_FA_SQUARE_X_TWITTER");
		ImGui::Text(ICON_FA_SQUARE_XING " || ICON_FA_SQUARE_XING");
		ImGui::Text(ICON_FA_SQUARE_YOUTUBE " || ICON_FA_SQUARE_YOUTUBE");
		ImGui::Text(ICON_FA_SQUARESPACE " || ICON_FA_SQUARESPACE");
		ImGui::Text(ICON_FA_STACK_EXCHANGE " || ICON_FA_STACK_EXCHANGE");
		ImGui::Text(ICON_FA_STACK_OVERFLOW " || ICON_FA_STACK_OVERFLOW");
		ImGui::Text(ICON_FA_STACKPATH " || ICON_FA_STACKPATH");
		ImGui::Text(ICON_FA_STAYLINKED " || ICON_FA_STAYLINKED");
		ImGui::Text(ICON_FA_STEAM " || ICON_FA_STEAM");
		ImGui::Text(ICON_FA_STEAM_SYMBOL " || ICON_FA_STEAM_SYMBOL");
		ImGui::Text(ICON_FA_STICKER_MULE " || ICON_FA_STICKER_MULE");
		ImGui::Text(ICON_FA_STRAVA " || ICON_FA_STRAVA");
		ImGui::Text(ICON_FA_STRIPE " || ICON_FA_STRIPE");
		ImGui::Text(ICON_FA_STRIPE_S " || ICON_FA_STRIPE_S");
		ImGui::Text(ICON_FA_STUBBER " || ICON_FA_STUBBER");
		ImGui::Text(ICON_FA_STUDIOVINARI " || ICON_FA_STUDIOVINARI");
		ImGui::Text(ICON_FA_STUMBLEUPON " || ICON_FA_STUMBLEUPON");
		ImGui::Text(ICON_FA_STUMBLEUPON_CIRCLE " || ICON_FA_STUMBLEUPON_CIRCLE");
		ImGui::Text(ICON_FA_SUPERPOWERS " || ICON_FA_SUPERPOWERS");
		ImGui::Text(ICON_FA_SUPPLE " || ICON_FA_SUPPLE");
		ImGui::Text(ICON_FA_SUSE " || ICON_FA_SUSE");
		ImGui::Text(ICON_FA_SWIFT " || ICON_FA_SWIFT");
		ImGui::Text(ICON_FA_SYMFONY " || ICON_FA_SYMFONY");
		ImGui::Text(ICON_FA_TEAMSPEAK " || ICON_FA_TEAMSPEAK");
		ImGui::Text(ICON_FA_TELEGRAM " || ICON_FA_TELEGRAM");
		ImGui::Text(ICON_FA_TENCENT_WEIBO " || ICON_FA_TENCENT_WEIBO");
		ImGui::Text(ICON_FA_THE_RED_YETI " || ICON_FA_THE_RED_YETI");
		ImGui::Text(ICON_FA_THEMECO " || ICON_FA_THEMECO");
		ImGui::Text(ICON_FA_THEMEISLE " || ICON_FA_THEMEISLE");
		ImGui::Text(ICON_FA_THINK_PEAKS " || ICON_FA_THINK_PEAKS");
		ImGui::Text(ICON_FA_THREADS " || ICON_FA_THREADS");
		ImGui::Text(ICON_FA_TIKTOK " || ICON_FA_TIKTOK");
		ImGui::Text(ICON_FA_TRADE_FEDERATION " || ICON_FA_TRADE_FEDERATION");
		ImGui::Text(ICON_FA_TRELLO " || ICON_FA_TRELLO");
		ImGui::Text(ICON_FA_TUMBLR " || ICON_FA_TUMBLR");
		ImGui::Text(ICON_FA_TWITCH " || ICON_FA_TWITCH");
		ImGui::Text(ICON_FA_TWITTER " || ICON_FA_TWITTER");
		ImGui::Text(ICON_FA_TYPO3 " || ICON_FA_TYPO3");
		ImGui::Text(ICON_FA_UBER " || ICON_FA_UBER");
		ImGui::Text(ICON_FA_UBUNTU " || ICON_FA_UBUNTU");
		ImGui::Text(ICON_FA_UIKIT " || ICON_FA_UIKIT");
		ImGui::Text(ICON_FA_UMBRACO " || ICON_FA_UMBRACO");
		ImGui::Text(ICON_FA_UNCHARTED " || ICON_FA_UNCHARTED");
		ImGui::Text(ICON_FA_UNIREGISTRY " || ICON_FA_UNIREGISTRY");
		ImGui::Text(ICON_FA_UNITY " || ICON_FA_UNITY");
		ImGui::Text(ICON_FA_UNSPLASH " || ICON_FA_UNSPLASH");
		ImGui::Text(ICON_FA_UNTAPPD " || ICON_FA_UNTAPPD");
		ImGui::Text(ICON_FA_UPS " || ICON_FA_UPS");
		ImGui::Text(ICON_FA_USB " || ICON_FA_USB");
		ImGui::Text(ICON_FA_USPS " || ICON_FA_USPS");
		ImGui::Text(ICON_FA_USSUNNAH " || ICON_FA_USSUNNAH");
		ImGui::Text(ICON_FA_VAADIN " || ICON_FA_VAADIN");
		ImGui::Text(ICON_FA_VIACOIN " || ICON_FA_VIACOIN");
		ImGui::Text(ICON_FA_VIADEO " || ICON_FA_VIADEO");
		ImGui::Text(ICON_FA_VIBER " || ICON_FA_VIBER");
		ImGui::Text(ICON_FA_VIMEO " || ICON_FA_VIMEO");
		ImGui::Text(ICON_FA_VIMEO_V " || ICON_FA_VIMEO_V");
		ImGui::Text(ICON_FA_VINE " || ICON_FA_VINE");
		ImGui::Text(ICON_FA_VK " || ICON_FA_VK");
		ImGui::Text(ICON_FA_VNV " || ICON_FA_VNV");
		ImGui::Text(ICON_FA_VUEJS " || ICON_FA_VUEJS");
		ImGui::Text(ICON_FA_WATCHMAN_MONITORING " || ICON_FA_WATCHMAN_MONITORING");
		ImGui::Text(ICON_FA_WAZE " || ICON_FA_WAZE");
		ImGui::Text(ICON_FA_WEEBLY " || ICON_FA_WEEBLY");
		ImGui::Text(ICON_FA_WEIBO " || ICON_FA_WEIBO");
		ImGui::Text(ICON_FA_WEIXIN " || ICON_FA_WEIXIN");
		ImGui::Text(ICON_FA_WHATSAPP " || ICON_FA_WHATSAPP");
		ImGui::Text(ICON_FA_WHMCS " || ICON_FA_WHMCS");
		ImGui::Text(ICON_FA_WIKIPEDIA_W " || ICON_FA_WIKIPEDIA_W");
		ImGui::Text(ICON_FA_WINDOWS " || ICON_FA_WINDOWS");
		ImGui::Text(ICON_FA_WIRSINDHANDWERK " || ICON_FA_WIRSINDHANDWERK");
		ImGui::Text(ICON_FA_WIX " || ICON_FA_WIX");
		ImGui::Text(ICON_FA_WIZARDS_OF_THE_COAST " || ICON_FA_WIZARDS_OF_THE_COAST");
		ImGui::Text(ICON_FA_WODU " || ICON_FA_WODU");
		ImGui::Text(ICON_FA_WOLF_PACK_BATTALION " || ICON_FA_WOLF_PACK_BATTALION");
		ImGui::Text(ICON_FA_WORDPRESS " || ICON_FA_WORDPRESS");
		ImGui::Text(ICON_FA_WORDPRESS_SIMPLE " || ICON_FA_WORDPRESS_SIMPLE");
		ImGui::Text(ICON_FA_WPBEGINNER " || ICON_FA_WPBEGINNER");
		ImGui::Text(ICON_FA_WPEXPLORER " || ICON_FA_WPEXPLORER");
		ImGui::Text(ICON_FA_WPFORMS " || ICON_FA_WPFORMS");
		ImGui::Text(ICON_FA_WPRESSR " || ICON_FA_WPRESSR");
		ImGui::Text(ICON_FA_X_TWITTER " || ICON_FA_X_TWITTER");
		ImGui::Text(ICON_FA_XBOX " || ICON_FA_XBOX");
		ImGui::Text(ICON_FA_XING " || ICON_FA_XING");
		ImGui::Text(ICON_FA_Y_COMBINATOR " || ICON_FA_Y_COMBINATOR");
		ImGui::Text(ICON_FA_YAHOO " || ICON_FA_YAHOO");
		ImGui::Text(ICON_FA_YAMMER " || ICON_FA_YAMMER");
		ImGui::Text(ICON_FA_YANDEX " || ICON_FA_YANDEX");
		ImGui::Text(ICON_FA_YANDEX_INTERNATIONAL " || ICON_FA_YANDEX_INTERNATIONAL");
		ImGui::Text(ICON_FA_YARN " || ICON_FA_YARN");
		ImGui::Text(ICON_FA_YELP " || ICON_FA_YELP");
		ImGui::Text(ICON_FA_YOAST " || ICON_FA_YOAST");
		ImGui::Text(ICON_FA_YOUTUBE " || ICON_FA_YOUTUBE");
		ImGui::Text(ICON_FA_ZHIHU " || ICON_FA_ZHIHU");
	}
}
